# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitoring_interface_0301.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectionFrame = QtWidgets.QFrame(self.centralwidget)
        self.connectionFrame.setGeometry(QtCore.QRect(20, 20, 191, 201))
        self.connectionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connectionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connectionFrame.setObjectName("connectionFrame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.connectionFrame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.connectionStatusLabel = QtWidgets.QLabel(self.connectionFrame)
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.connectionStatusLabel)
        self.targetComConnectButton = QtWidgets.QPushButton(self.connectionFrame)
        self.targetComConnectButton.setObjectName("targetComConnectButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.targetComConnectButton)
        self.updateCOMButton = QtWidgets.QPushButton(self.connectionFrame)
        self.updateCOMButton.setObjectName("updateCOMButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.updateCOMButton)
        self.targetComCB = QtWidgets.QComboBox(self.connectionFrame)
        self.targetComCB.setObjectName("targetComCB")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.targetComCB)
        self.targetComLabel = QtWidgets.QLabel(self.connectionFrame)
        self.targetComLabel.setObjectName("targetComLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.targetComLabel)
        self.tabWidgetGraphs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetGraphs.setGeometry(QtCore.QRect(220, 20, 1047, 675))
        self.tabWidgetGraphs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidgetGraphs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidgetGraphs.setIconSize(QtCore.QSize(16, 16))
        self.tabWidgetGraphs.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidgetGraphs.setUsesScrollButtons(True)
        self.tabWidgetGraphs.setDocumentMode(False)
        self.tabWidgetGraphs.setTabsClosable(False)
        self.tabWidgetGraphs.setMovable(False)
        self.tabWidgetGraphs.setTabBarAutoHide(False)
        self.tabWidgetGraphs.setObjectName("tabWidgetGraphs")
        self.M10 = QtWidgets.QWidget()
        self.M10.setObjectName("M10")
        self.frameMinMaxAM10 = QtWidgets.QFrame(self.M10)
        self.frameMinMaxAM10.setGeometry(QtCore.QRect(950, 60, 91, 151))
        self.frameMinMaxAM10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMinMaxAM10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMinMaxAM10.setObjectName("frameMinMaxAM10")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameMinMaxAM10)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxLineChoiceAM10 = QtWidgets.QComboBox(self.frameMinMaxAM10)
        self.comboBoxLineChoiceAM10.setObjectName("comboBoxLineChoiceAM10")
        self.verticalLayout.addWidget(self.comboBoxLineChoiceAM10)
        self.labelMinLineAM10 = QtWidgets.QLabel(self.frameMinMaxAM10)
        self.labelMinLineAM10.setObjectName("labelMinLineAM10")
        self.verticalLayout.addWidget(self.labelMinLineAM10)
        self.labelMaxLineAM10 = QtWidgets.QLabel(self.frameMinMaxAM10)
        self.labelMaxLineAM10.setObjectName("labelMaxLineAM10")
        self.verticalLayout.addWidget(self.labelMaxLineAM10)
        self.frameMinMaxBM10 = QtWidgets.QFrame(self.M10)
        self.frameMinMaxBM10.setGeometry(QtCore.QRect(950, 420, 91, 151))
        self.frameMinMaxBM10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMinMaxBM10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMinMaxBM10.setObjectName("frameMinMaxBM10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameMinMaxBM10)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBoxLineChoiceBM10 = QtWidgets.QComboBox(self.frameMinMaxBM10)
        self.comboBoxLineChoiceBM10.setObjectName("comboBoxLineChoiceBM10")
        self.verticalLayout_2.addWidget(self.comboBoxLineChoiceBM10)
        self.labelMinLineBM10 = QtWidgets.QLabel(self.frameMinMaxBM10)
        self.labelMinLineBM10.setObjectName("labelMinLineBM10")
        self.verticalLayout_2.addWidget(self.labelMinLineBM10)
        self.labelMaxLineBM10 = QtWidgets.QLabel(self.frameMinMaxBM10)
        self.labelMaxLineBM10.setObjectName("labelMaxLineBM10")
        self.verticalLayout_2.addWidget(self.labelMaxLineBM10)
        self.graphWindowM10 = GraphicsLayoutWidget(self.M10)
        self.graphWindowM10.setGeometry(QtCore.QRect(0, 40, 931, 609))
        self.graphWindowM10.setObjectName("graphWindowM10")
        self.tabWidgetGraphs.addTab(self.M10, "")
        self.M14 = QtWidgets.QWidget()
        self.M14.setObjectName("M14")
        self.frameMinMaxAM14 = QtWidgets.QFrame(self.M14)
        self.frameMinMaxAM14.setGeometry(QtCore.QRect(950, 60, 91, 151))
        self.frameMinMaxAM14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMinMaxAM14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMinMaxAM14.setObjectName("frameMinMaxAM14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameMinMaxAM14)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBoxLineChoiceAM14 = QtWidgets.QComboBox(self.frameMinMaxAM14)
        self.comboBoxLineChoiceAM14.setObjectName("comboBoxLineChoiceAM14")
        self.verticalLayout_3.addWidget(self.comboBoxLineChoiceAM14)
        self.labelMinLineAM14 = QtWidgets.QLabel(self.frameMinMaxAM14)
        self.labelMinLineAM14.setObjectName("labelMinLineAM14")
        self.verticalLayout_3.addWidget(self.labelMinLineAM14)
        self.labelMaxLineAM14 = QtWidgets.QLabel(self.frameMinMaxAM14)
        self.labelMaxLineAM14.setObjectName("labelMaxLineAM14")
        self.verticalLayout_3.addWidget(self.labelMaxLineAM14)
        self.frameMinMaxBM14 = QtWidgets.QFrame(self.M14)
        self.frameMinMaxBM14.setGeometry(QtCore.QRect(950, 420, 91, 151))
        self.frameMinMaxBM14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMinMaxBM14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMinMaxBM14.setObjectName("frameMinMaxBM14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameMinMaxBM14)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBoxLineChoiceBM14 = QtWidgets.QComboBox(self.frameMinMaxBM14)
        self.comboBoxLineChoiceBM14.setObjectName("comboBoxLineChoiceBM14")
        self.verticalLayout_4.addWidget(self.comboBoxLineChoiceBM14)
        self.labelMinLineBM14 = QtWidgets.QLabel(self.frameMinMaxBM14)
        self.labelMinLineBM14.setObjectName("labelMinLineBM14")
        self.verticalLayout_4.addWidget(self.labelMinLineBM14)
        self.labelMaxLineBM14 = QtWidgets.QLabel(self.frameMinMaxBM14)
        self.labelMaxLineBM14.setObjectName("labelMaxLineBM14")
        self.verticalLayout_4.addWidget(self.labelMaxLineBM14)
        self.graphWindowM14 = GraphicsLayoutWidget(self.M14)
        self.graphWindowM14.setGeometry(QtCore.QRect(0, 40, 931, 609))
        self.graphWindowM14.setObjectName("graphWindowM14")
        self.tabWidgetGraphs.addTab(self.M14, "")
        self.G10 = QtWidgets.QWidget()
        self.G10.setObjectName("G10")
        self.graphWindowG10 = GraphicsLayoutWidget(self.G10)
        self.graphWindowG10.setGeometry(QtCore.QRect(0, 40, 931, 609))
        self.graphWindowG10.setObjectName("graphWindowG10")
        self.tabWidgetGraphs.addTab(self.G10, "")
        self.G14 = QtWidgets.QWidget()
        self.G14.setObjectName("G14")
        self.graphWindowG14 = GraphicsLayoutWidget(self.G14)
        self.graphWindowG14.setGeometry(QtCore.QRect(0, 40, 931, 609))
        self.graphWindowG14.setObjectName("graphWindowG14")
        self.tabWidgetGraphs.addTab(self.G14, "")
        self.sensorEntryListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.sensorEntryListWidget.setGeometry(QtCore.QRect(20, 250, 189, 441))
        self.sensorEntryListWidget.setDragEnabled(True)
        self.sensorEntryListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.sensorEntryListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sensorEntryListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sensorEntryListWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.sensorEntryListWidget.setSelectionRectVisible(False)
        self.sensorEntryListWidget.setObjectName("sensorEntryListWidget")
        self.sensorEntryLabel = QtWidgets.QLabel(self.centralwidget)
        self.sensorEntryLabel.setGeometry(QtCore.QRect(20, 230, 189, 13))
        self.sensorEntryLabel.setWordWrap(True)
        self.sensorEntryLabel.setObjectName("sensorEntryLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidgetGraphs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectionStatusLabel.setText(_translate("MainWindow", "Connection Status: Offline"))
        self.targetComConnectButton.setText(_translate("MainWindow", "Connect"))
        self.updateCOMButton.setText(_translate("MainWindow", "Update COM List"))
        self.targetComLabel.setText(_translate("MainWindow", "Target COM:"))
        self.labelMinLineAM10.setText(_translate("MainWindow", "Min:"))
        self.labelMaxLineAM10.setText(_translate("MainWindow", "Max:"))
        self.labelMinLineBM10.setText(_translate("MainWindow", "Min:"))
        self.labelMaxLineBM10.setText(_translate("MainWindow", "Max:"))
        self.tabWidgetGraphs.setTabText(self.tabWidgetGraphs.indexOf(self.M10), _translate("MainWindow", "                                     M10                                    "))
        self.labelMinLineAM14.setText(_translate("MainWindow", "Min:"))
        self.labelMaxLineAM14.setText(_translate("MainWindow", "Max:"))
        self.labelMinLineBM14.setText(_translate("MainWindow", "Min:"))
        self.labelMaxLineBM14.setText(_translate("MainWindow", "Max:"))
        self.tabWidgetGraphs.setTabText(self.tabWidgetGraphs.indexOf(self.M14), _translate("MainWindow", "                                    M14                                   "))
        self.tabWidgetGraphs.setTabText(self.tabWidgetGraphs.indexOf(self.G10), _translate("MainWindow", "                                    G10                                    "))
        self.tabWidgetGraphs.setTabText(self.tabWidgetGraphs.indexOf(self.G14), _translate("MainWindow", "                                      G14                                     "))
        self.sensorEntryLabel.setText(_translate("MainWindow", "Module                   Time"))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

