# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitoring_interface_01.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectionFrame = QtWidgets.QFrame(self.centralwidget)
        self.connectionFrame.setGeometry(QtCore.QRect(20, 20, 191, 91))
        self.connectionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connectionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connectionFrame.setObjectName("connectionFrame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.connectionFrame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.targetComLabel = QtWidgets.QLabel(self.connectionFrame)
        self.targetComLabel.setObjectName("targetComLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.targetComLabel)
        self.targetComConnectButton = QtWidgets.QPushButton(self.connectionFrame)
        self.targetComConnectButton.setObjectName("targetComConnectButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.targetComConnectButton)
        self.targetComCB = QtWidgets.QComboBox(self.connectionFrame)
        self.targetComCB.setObjectName("targetComCB")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.targetComCB)
        self.connectionStatusLabel = QtWidgets.QLabel(self.connectionFrame)
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.connectionStatusLabel)
        self.updateCOMButton = QtWidgets.QPushButton(self.connectionFrame)
        self.updateCOMButton.setObjectName("updateCOMButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.updateCOMButton)
        self.toolsFrame = QtWidgets.QFrame(self.centralwidget)
        self.toolsFrame.setGeometry(QtCore.QRect(20, 130, 191, 541))
        self.toolsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolsFrame.setObjectName("toolsFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.toolsFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolsFiltersGroupBox = QtWidgets.QGroupBox(self.toolsFrame)
        self.toolsFiltersGroupBox.setEnabled(True)
        self.toolsFiltersGroupBox.setAutoFillBackground(False)
        self.toolsFiltersGroupBox.setFlat(False)
        self.toolsFiltersGroupBox.setCheckable(True)
        self.toolsFiltersGroupBox.setChecked(False)
        self.toolsFiltersGroupBox.setObjectName("toolsFiltersGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolsFiltersGroupBox)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slavesComboBox = QtWidgets.QComboBox(self.toolsFiltersGroupBox)
        self.slavesComboBox.setObjectName("slavesComboBox")
        self.horizontalLayout.addWidget(self.slavesComboBox)
        self.sensorsComboBox = QtWidgets.QComboBox(self.toolsFiltersGroupBox)
        self.sensorsComboBox.setObjectName("sensorsComboBox")
        self.horizontalLayout.addWidget(self.sensorsComboBox)
        self.verticalLayout.addWidget(self.toolsFiltersGroupBox)
        self.sensorEntryLabel = QtWidgets.QLabel(self.toolsFrame)
        self.sensorEntryLabel.setWordWrap(True)
        self.sensorEntryLabel.setObjectName("sensorEntryLabel")
        self.verticalLayout.addWidget(self.sensorEntryLabel)
        self.sensorEntryListWidget = QtWidgets.QListWidget(self.toolsFrame)
        self.sensorEntryListWidget.setDragEnabled(True)
        self.sensorEntryListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.sensorEntryListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sensorEntryListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sensorEntryListWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.sensorEntryListWidget.setSelectionRectVisible(False)
        self.sensorEntryListWidget.setObjectName("sensorEntryListWidget")
        self.verticalLayout.addWidget(self.sensorEntryListWidget)
        self.graphFrame = graphQFrame(self.centralwidget)
        self.graphFrame.setGeometry(QtCore.QRect(230, 20, 1021, 651))
        self.graphFrame.setAcceptDrops(True)
        self.graphFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.graphFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graphFrame.setObjectName("graphFrame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuGraph = QtWidgets.QMenu(self.menuBar)
        self.menuGraph.setObjectName("menuGraph")
        self.menuSlaves = QtWidgets.QMenu(self.menuBar)
        self.menuSlaves.setObjectName("menuSlaves")
        self.menuPrototypes = QtWidgets.QMenu(self.menuBar)
        self.menuPrototypes.setObjectName("menuPrototypes")
        MainWindow.setMenuBar(self.menuBar)
        self.actionClear_Graph = QtWidgets.QAction(MainWindow)
        self.actionClear_Graph.setObjectName("actionClear_Graph")
        self.actionSave_File = QtWidgets.QAction(MainWindow)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSlavesEdit = QtWidgets.QAction(MainWindow)
        self.actionSlavesEdit.setObjectName("actionSlavesEdit")
        self.actionSlavesAdd = QtWidgets.QAction(MainWindow)
        self.actionSlavesAdd.setObjectName("actionSlavesAdd")
        self.actionPrototypesEdit = QtWidgets.QAction(MainWindow)
        self.actionPrototypesEdit.setObjectName("actionPrototypesEdit")
        self.actionPrototypesAdd = QtWidgets.QAction(MainWindow)
        self.actionPrototypesAdd.setObjectName("actionPrototypesAdd")
        self.menuFile.addAction(self.actionSave_File)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuGraph.addAction(self.actionClear_Graph)
        self.menuSlaves.addAction(self.actionSlavesEdit)
        self.menuSlaves.addAction(self.actionSlavesAdd)
        self.menuPrototypes.addAction(self.actionPrototypesEdit)
        self.menuPrototypes.addAction(self.actionPrototypesAdd)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuGraph.menuAction())
        self.menuBar.addAction(self.menuSlaves.menuAction())
        self.menuBar.addAction(self.menuPrototypes.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Monitoring Interface V0.1 - Pavnext"))
        self.targetComLabel.setText(_translate("MainWindow", "Target COM:"))
        self.targetComConnectButton.setText(_translate("MainWindow", "Connect"))
        self.connectionStatusLabel.setText(_translate("MainWindow", "Connection Status: Offline"))
        self.updateCOMButton.setText(_translate("MainWindow", "Update COM List"))
        self.toolsFiltersGroupBox.setTitle(_translate("MainWindow", "Filters"))
        self.sensorEntryLabel.setText(_translate("MainWindow", "  S#S#                ID                   Size"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuGraph.setTitle(_translate("MainWindow", "Graph"))
        self.menuSlaves.setTitle(_translate("MainWindow", "Slaves"))
        self.menuPrototypes.setTitle(_translate("MainWindow", "Prototypes"))
        self.actionClear_Graph.setText(_translate("MainWindow", "Clear Graph"))
        self.actionSave_File.setText(_translate("MainWindow", "Save File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionSlavesEdit.setText(_translate("MainWindow", "Edit"))
        self.actionSlavesAdd.setText(_translate("MainWindow", "Add"))
        self.actionPrototypesEdit.setText(_translate("MainWindow", "Edit"))
        self.actionPrototypesAdd.setText(_translate("MainWindow", "Add"))

from gui.guiutility import graphQFrame

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

